pipeline {
  agent any
  
  tools {
    nodejs 'node10.15.2'
  }

  stages {
        stage('checking') {
          steps {
            sh 'ng --version'
          }
        }
        
        stage('Build') {
          steps {
            git branch: 'develop', url: 'https://github.com/myx4play/poc-angular-ci'
            dir('my-app') {
              sh 'ls'
              sh 'npm install'
            }
            
          }
        }
    
        stage('Unit Test') {
          steps {
            echo 'NOT unit test YET.'
          }
        }
    
        stage('Development Deploy') {
            parallel {
                stage('develop') {
                    when {
                        branch 'develop'  
                    }
                    steps {
                      sh './jenkins/scripts/develop-script.sh'
                      input message: 'Finished using the web site? (Click "Proceed" to continue)'
                    }
                }
                
                stage('planning') {
                    when {
                        branch 'planning'  
                    }
                    steps {
                        sh './jenkins/scripts/planning-script.sh'
                        input message: 'Finished using the web site? (Click "Proceed" to continue)'
                    }
                }
            }
        }

        stage('Teardown') {
          steps {
            sh './jenkins/scripts/kill.sh'
          }
        }
    }  
}
