pipeline {
  agent any
  
  tools {
    nodejs 'node10.15.2'
  }

  stages {
        stage('checking') {
          steps {
            sh 'ng --version'
          }
        }
        
        stage('Build') {
          steps {
            dir('my-app') {
              sh 'ls'
              sh 'npm install'
            }
          }
        }
    
        stage('Unit Test') {
          steps {
            echo 'NOT unit test YET.'
          }
        }
    
        stage('Deploy for Develop') {
            when {
                branch 'develop'  
            }
            steps {
              sh './jenkins/scripts/develop-script.sh'
              input message: 'Finished using the web site? (Click "Proceed" to continue)'
              sh './jenkins/scripts/kill.sh'
            }
        }
    
        stage('Deploy for Planning Features') {
            when {
                branch 'planning'  
            }
            steps {
                sh './jenkins/scripts/planning-script.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }  
}
