pipeline {
  agent any
  
  tools {
    nodejs 'node6.11.2'
  }

  stages {
    stage('Build') {
      parallel {
        stage('Build project') {
          steps {
            sh 'cd my-app'
            sh 'npm install'
          }
        }
        stage('Check versoin') {
          steps {
            sh 'node -v'
            sh 'npm -v'
            sh 'ng --version'
          }
        }
      }
    }
  }
  
}